language: node_js
node_js:
  - lts/*
cache:
  directories:
  - node_modules
install:
  - npm install
  - rm -rf themes/next
  - git clone https://github.com/theme-next/hexo-theme-next themes/next
  - cd themes/next
  - git clone https://github.com/theme-next/theme-next-algolia-instant-search source/lib/algolia-instant-search
  - git clone https://github.com/theme-next/theme-next-fancybox3 source/lib/fancybox
  - git clone https://github.com/theme-next/theme-next-pace source/lib/pace
  - git clone https://github.com/theme-next/theme-next-reading-progress source/lib/reading_progress
  - git clone https://github.com/theme-next/theme-next-needmoreshare2 source/lib/needsharebutton
  - git clone https://github.com/theme-next/theme-next-three source/lib/three
  - cd ../..
script:
  - npm run algolia
  - npm run predeploy
after_success:
  - cd public
  - git init
  - git config user.name "YunYouJun"
  - git config user.email "me@yunyoujun.cn"
  - git add .
  - git commit -m "Update Hexo Blog"
  - git push --force "https://${GH_TOKEN}@${GH_REF}" master:master
  - git push --force "https://yunyoujun:${CODING_TOKEN}@${CD_REF}" master:master
branches:
  only:
    - hexo
env:
  global:
    - GH_REF: github.com/YunYouJun/yunyoujun.github.io.git
    - CD_REF: git.coding.net/YunYouJun/yunyoujun.coding.me.git
