language: node_js
os: linux
node_js:
  - lts/*

before_install:
  - export TZ='Asia/Shanghai'

install:
  - npm install
  - git clone https://github.com/YunYouJun/hexo-theme-yun.git themes/yun

script:
  - npm run algolia
  - npm run predeploy

deploy:
  edge: true
  provider: pages
  token: $GH_TOKEN
  target_branch: master
  local_dir: public
  on:
    branch: hexo
