language: node_js
node_js:
  - lts/*

# cache:
#   directories:
#   - node_modules

branches:
  only:
    - hexo

before_install: 
  - export TZ='Asia/Shanghai'

install:
  - npm install
  - git clone https://github.com/YunYouJun/hexo-theme-starry.git themes/starry

script:
  - npm run algolia
  - npm run predeploy

deploy:
  provider: pages
  token: $GH_TOKEN
  target-branch: master
  local-dir: public
  on:
    branch: hexo

after_success:
  - cd public
  - git init
  - git config user.name "YunYouJun"
  - git config user.email "me@yunyoujun.cn"
  - git add .
  - git commit -m "deploy hexo blog"
  - git push --force "https://yunyoujun:${CODING_TOKEN}@${CD_REF}" master:master

env:
  global:
    - CD_REF='git.dev.tencent.com/YunYouJun/yunyoujun.coding.me.git'