language: node_js
node_js:
- lts/*
cache:
  directories:
  - node_modules
install:
- npm install
script:
- npm run deploy
before_install:
- openssl aes-256-cbc -K $encrypted_8f758fb5d001_key -iv $encrypted_8f758fb5d001_iv
  -in travis_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- git config --global user.name "YunYouJun"
- git config --global user.email me@yunyoujun.cn
branches:
  only:
  - hexo
