language: node_js
node_js:
  - lts/*
cache:
  directories:
  - node_modules
install:
  - npm install
script:
  - npm run predeploy
before_install:
  - git config --global user.name "YunYouJun"
  - git config --global user.email me@yunyoujun.cn
after_success:
  - cd public
  - git init
  - git add .
  - git commit -m "Update Hexo Blog"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
  - git push --force --quiet "https://${CODING_TOKEN}@${CD_REF}" master:master
branches:
  only:
    - hexo
env:
  global:
    - GH_REF: github.com/YunYouJun/yunyoujun.github.io.git
    - CD_REF: git.coding.net/YunYouJun/yunyoujun.coding.me.git
